services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\PlaceholderTimeBundle\:
        resource: '../../*'
        exclude: '../../{Resources,.github}'
